[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"


[project]
name = "shopping-cart"
version = "1.0.0"
description = "Shopping cart calculation system"
requires-python = ">=3.9"
dependencies = []


[project.optional-dependencies]
test = [
    "pytest>=7.0"
]


[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]